### PR TITLE
Fix for issue #182

### PR DESCRIPTION
**Pull request by borianm**
Now it doesn't throw an error, checked locally

### CODE REVIEW

**Comment by Alevale** [comment]
Just adding a link in order to make it easier to browse through :) https://github.com/DoctorMcKay/node-steamcommunity/issues/182

Just wanting to be picky, do we want to add some tests? :)

**Comment by borianm** [comment]
How do you want me to test it and show the results?

**Comment by Alevale** [comment]
> How do you want me to test it and show the results?

After thinking it through, and seeing there are no tests in the library, maybe it's not a good idea.

This said, looks good to me, so when @DoctorMcKay or whoever has right to merge this is happy with it maybe it can be merged ^^

**Comment by borianm** [comment]
It would be really useful to either merge this or create an alt solution but obviously if you have events in your group you can't even fetch announcements.

**Comment by DoctorMcKay** [comment]
:+1: Thanks. I'll go ahead and push an update for this.

**Pull request merged**
