### PR TITLE
Update profile.js

### PR DESCRIPTION
**Pull request by Kasp42**
Add showcase
Value: 1 Name showcase: Rarest Achievement Showcase
Value: 2 Name showcase: Game Collector
Value: 3 Name showcase: Item Showcase
Value: 4 Name showcase: Items Up For Trade
Value: 5 Name showcase: Badge Collector
Value: 6 Name showcase: Favorite Game
Value: 7 Name showcase: Screenshot Showcase
Value: 8 Name showcase: Custom Info Box
Value: 9 Name showcase: Favorite Group
Value: 10 Name showcase: Review Showcase
Value: 11 Name showcase: Workshop Showcase
Value: 13 Name showcase: Artwork Showcase
Value: 15 Name showcase: Favorite Guide
Value: 17 Name showcase: Achievement Showcase

### CODE REVIEW

**Comment by DoctorMcKay** [comment]
I'd rather do it in a more proper way when it's added.

**Comment by Kasp42** [comment]
I do not really know how to improve this code block as each showcase different parameters.
For example, at the window 17, here are the parameters:
```
{
	"rgShowcaseConfig[17][0][appid]": "266010",
	"rgShowcaseConfig[17][0][title]": "3_17",
	"rgShowcaseConfig[17][1][appid]": "266010",
	"rgShowcaseConfig[17][1][title]": "3_7",
	"rgShowcaseConfig[17][2][appid]": "266010",
	"rgShowcaseConfig[17][2][title]": "3_25",
	"rgShowcaseConfig[17][3][appid]": "266010",
	"rgShowcaseConfig[17][3][title]": "3_22",
	"rgShowcaseConfig[17][4][appid]": "266010",
	"rgShowcaseConfig[17][4][title]": "3_11",
	"rgShowcaseConfig[17][5][appid]": "266010",
	"rgShowcaseConfig[17][5][title]": "3_24",
	"rgShowcaseConfig[17][6][appid]": "266010",
	"rgShowcaseConfig[17][6][title]": "3_1"
}
```

**Comment by Kasp42** [comment]
Maybe so [patch-1](https://github.com/DoctorMcKay/node-steamcommunity/compare/master...Kasp42:patch-2)
Use:
```
community.editProfile({
	"summary": def + text,
	"showcases": {
		"8": [
			{
				"title": "title",
				"notes": "notes"
			}
		],
		"9": [
			{
				"accountid": "26639694"
			}
		],
		"17": [
			{
				"appid": "266010",
				"title": "3_17"
			},
			{
				"appid": "266010",
				"title": "3_7"
			},
			{
				"appid": "266010",
				"title": "3_25"
			},
			{
				"appid": "266010",
				"title": "3_22"
			},
			{
				"appid": "266010",
				"title": "3_11"
			},
			{
				"appid": "266010",
				"title": "3_24"
			},
			{
				"appid": "266010",
				"title": "3_1"
			}
		]
	}
});
```

**Comment by Kondax** [comment]
Personally I think your implementation is poor. It would make much more sense to configure the showcases by Objects rather than functional - just like the `SteamID` Object.

**Pull request closed without merging**
