### PR TITLE
Flag to disable mobile login

### PR DESCRIPTION
**Pull request by potato20**
In some cases i prefer to not pretend to login from a phone, so i added this flag.

### CODE REVIEW

**Comment by DoctorMcKay** [comment]
For what purpose?

**Comment by potato20** [comment]
The `steamRememberLogin` cookie doesn't get sent back from the server if you're signing in from mobile, even though you're passing in `"remember_login": "true"` [here](https://github.com/DoctorMcKay/node-steamcommunity/blob/master/index.js#L114).

**Comment by potato20** [comment]
@DoctorMcKay Thanks for the merge. did you want to leave a closing comment? It's been almost a year.

**Comment by DoctorMcKay** [comment]
I'll try to push this out to npm today.

**Pull request merged**
